apiVersion: apps/v1
metadata:
   name: frontend
kind: Deployment
spec:
     replicas : 3 
     selector:
        matchLabels:
          
          app: frontend 
     template:
        metadata:
          labels:
             app: frontend
        spec:
          containers:
          - name: cnt-1
            image:  flask-app:9ecbc60846a1d925bb55e9f8a5dec0e7994fd9b7
            ports:
            - containerPort: 8080