apiVersion: apps/v1
metadata:
   name: frontend
kind: Deployment
spec:
     replicas : 3 
     selector:
        matchLabels:
          
          app: frontend 
     template:
        metadata:
          labels:
             app: frontend
        spec:
          containers:
          - name: cnt-1
<<<<<<< HEAD
            image:  asia-south2-docker.pkg.dev/cobalt-infinity-405312/repo-github/frontend:v4
=======
            image:  flask-app:9ecbc60846a1d925bb55e9f8a5dec0e7994fd9b7
>>>>>>> 925c157faf5ac5c8b2573f29bbc1caf80f5621a7
            ports:
            - containerPort: 8080