apiVersion: apps/v1
metadata:
   name: frontend
kind: Deployment
spec:
     replicas : 3 
     selector:
        matchLabels:
          
          app: frontend 
     template:
        metadata:
          labels:
             app: frontend
        spec:
          containers:
          - name: cnt-1
            image:  asia-south2-docker.pkg.dev/cobalt-infinity-405312/repo-github/frontend:v4
            ports:
            - containerPort: 8080