run-name: gcp-deploy-run
name: gcp-deploy
on:
   push:
      paths: 
      - "app/**"
env:
  PROJECT_ID: "cobalt-infinity-405312"
  GAR_LOCATION: "asia-south2"
  REGISTRY_NAME: "github-repo"
jobs:
    deploy_to_gcp:
      permissions:
         id-token: write
         contents: write
      runs-on: ubuntu-latest
      steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Google Auth
        id: auth
        uses: 'google-github-actions/auth@v0'
        with:
          token_format: 'access_token'
          workload_identity_provider: '${{ secrets.WIF_PROVIDER }}' # e.g. - projects/123456789/locations/global/workloadIdentityPools/my-pool/providers/my-provider
          service_account: '${{ secrets.WIF_SERVICE_ACCOUNT }}'
      - name: Docker Auth
        id: docker-auth
        uses: 'docker/login-action@v1'
        with:
          username: 'oauth2accesstoken'
          password: '${{ steps.auth.outputs.access_token }}'
          registry: '${{ env.GAR_LOCATION }}-docker.pkg.dev'
      - name : move to app directory
        run: cd app

      - name: Build and Push Container
        run: |
          docker build -t "${{ env.GAR_LOCATION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.REGISTRY_NAME }}:${{ github.sha }}" 
          docker push "${{ env.GAR_LOCATION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.REGISTRY_NAME }}:${{ github.sha }}"
      
      - name:  apply image tag to deployment file also to start cd
        run: |
            cd ..
            sed -i "s/flask-app.*$/flask-app:${{github.sha}}/" k8s-files/deployment.yaml
      - name: Commit files
        run: |
          
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git commit -a -m "Add changes"
      - name: push-to-repo 
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}